[package]
name = "MineGit"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
flate2 = { version = "1.0", features = ["miniz-sys"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

# other deps
byteorder = "1.5.0"
divsufsort = "1.0.2"
libdeflater = "1.23.1"